### ISSUE TITLE
Can not find strscan

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlss-capistrano#39]
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
      01 bash: -c: line 0: unexpected EOF while looking for matching ``'
      01 bash: -c: line 1: syntax error: unexpected end of file
#<Thread:0x000000010bdd6420 /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as pres@preservation-catalog-prod-02.stanford.edu: gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' exit status: 1 (SSHKit::Runner::ExecuteError)
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stdout: bash: -c: line 0: unexpected EOF while looking for matching ``'\r
bash: -c: line 1: syntax error: unexpected end of file
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stderr: Nothing written
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' exit status: 1 (SSHKit::Command::Failed)
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stdout: bash: -c: line 0: unexpected EOF while looking for matching ``'\r
bash: -c: line 1: syntax error: unexpected end of file
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stderr: Nothing written
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:170:in `execute_command'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	from <internal:kernel>:90:in `tap'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dlss-capistrano-4.2.1/lib/dlss/capistrano/tasks/strscan.rake:11:in `block (2 levels) in <top (required)>'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

If I bypass capistrano, and ssh to the server and run the command I get an error too:
```
pres@preservation-catalog-prod-02:~/preservation_catalog/current$ bundle exec ruby -e "puts Gem::Specification.find_by_name('strscan').version"
/usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information
	from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'
	from -e:1:in `<main>'
```

**Comment by jcoyne** [comment]
On stage:
```
➜  preservation_catalog git:(main) HOSTS=preservation-catalog-web-stage-01.stanford.edu cap stage update_global_strscan
Pseudo-terminal will not be allocated because stdin is not a terminal.
rvm 1.29.12 (1.29.12) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
ruby-3.0.3
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
00:00 update_global_strscan
      WARN  strscan is not installed
Pseudo-terminal will not be allocated because stdin is not a terminal.
```


On prod:
```
 HOSTS=preservation-catalog-prod-02.stanford.edu cap prod update_global_strscan
Pseudo-terminal will not be allocated because stdin is not a terminal.
rvm 1.29.12 (1.29.12) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
ruby-3.0.3
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
00:00 update_global_strscan
      01 gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/depende…
      01 bash: -c: line 0: unexpected EOF while looking for matching ``'
      01 bash: -c: line 1: syntax error: unexpected end of file
#<Thread:0x00000001051043d8 /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as pres@preservation-catalog-prod-02.stanford.edu: gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' exit status: 1 (SSHKit::Runner::ExecuteError)
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stdout: bash: -c: line 0: unexpected EOF while looking for matching ``'\r
bash: -c: line 1: syntax error: unexpected end of file
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stderr: Nothing written
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' exit status: 1 (SSHKit::Command::Failed)
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stdout: bash: -c: line 0: unexpected EOF while looking for matching ``'\r
bash: -c: line 1: syntax error: unexpected end of file
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': \e[1mCould not find 'strscan' (>= 0) among 210 total gem(s) (\e[1;4mGem::MissingSpecError\e[m\e[1m)\e[m; \e[1mChecked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information\e[m; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stderr: Nothing written
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:170:in `execute_command'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	from <internal:kernel>:90:in `tap'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dlss-capistrano-4.2.1/lib/dlss/capistrano/tasks/strscan.rake:11:in `block (2 levels) in <top (required)>'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as pres@preservation-catalog-prod-02.stanford.edu: gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError); Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' exit status: 1
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError); Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stdout: bash: -c: line 0: unexpected EOF while looking for matching ``'
bash: -c: line 1: syntax error: unexpected end of file
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError); Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stderr: Nothing written


Caused by:
SSHKit::Command::Failed: gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError); Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' exit status: 1
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError); Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stdout: bash: -c: line 0: unexpected EOF while looking for matching ``'
bash: -c: line 1: syntax error: unexpected end of file
gem install strscan --silent --no-document -v /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'strscan' (>= 0) among 210 total gem(s) (Gem::MissingSpecError); Checked in 'GEM_PATH=/opt/app/pres/preservation_catalog/shared/bundle/ruby/3.0.0' , execute `gem env` for more information; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'; from /usr/local/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'; from -e:1:in `<main>' stderr: Nothing written
/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dlss-capistrano-4.2.1/lib/dlss/capistrano/tasks/strscan.rake:11:in `block (2 levels) in <top (required)>'
Tasks: TOP => update_global_strscan
(See full trace by running task with --trace)
Pseudo-terminal will not be allocated because stdin is not a terminal.
```
